### ISSUE TITLE
Novos Updates ou "Abandonado"

### ISSUE THREAD

**Issue by willph** [DoocaCommerce/PagHiper-PHP-SDK#2]
Gostaria de saber se esta atualizado para a versão mais recente do PagHiper?

Ou se sua versão foi "abandonada"?

**Comment by arthurlauck** [comment]
Estamos utilizando em produção esse pacote, não tivemos necessidade de atualizações até agora, se tivermos iremos atualizar.

**Comment by arthurlauck** [comment]
Teria alguma coisa faltando?

**Comment by willph** [comment]
Não, era só pra saber para não usar algo que está "abandonado", entende? 

Obrigado pela resposta!

**Comment by willph** [comment]
> 
> 
> Teria alguma coisa faltando?

Posso usar nesse projeto que é gratuito? 

https://github.com/RamonSilva20/mapos/

**Comment by arthurlauck** [comment]
Claro, liberado! Se encontrar alguma coisa que possa ser alterado, só abrir issue ou pull request!
